<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
    <PackageReference Include="Microsoft.ML.Tokenizers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DcResearchMcp.Core\DcResearchMcp.Core.csproj" />
  </ItemGroup>

</Project>
